### ISSUE TITLE
Release as separate skin?

### ISSUE THREAD

**Issue by der-tkw** [un1versal/revamped.themes#1]
Hi there,

I don't know if this is possible or legally doable, but would it be possible to release this as a new skin? - There is for example no way to use this on Kodi with Amazon Fire (unrooted). I mean the installation is not really hard but if you want to use it with every RC etc or Nighlies it becomes a littl, the skin on the contrary would just stay in the user folder which doesn't change.

Keep up the great work,
Tim

**Comment by un1versal** [comment]
You can do that, its perfectly ok, but I can tell you keeping skin updated is a nightmare, I use to do that for a while.

Just add the theme to default skin and not worry about keeping skin up-to-date is also the ideal route for this really matters not the skin version, just make it Confluence skin and you dont have to worry about skin versions, skin themes do not break..

If you like feel free to do that, its both legal and encouraged. My bits are all gplv2 or public domain or similar.

There other skins that use these graphics like http://forum.xbmc.org/showthread.php?tid=198920

If you do release shoot me a link and give some credits on the changelog, :+1:

**Comment by der-tkw** [comment]
Your approach is perfectly fine for most of my devices (iPad, iPhone, OS X). But since my Fire TV is not rooted and on Android the default Confluence skin is in some strange location (not in the default addons folder) I needed another approach. Using the default Confluence skin, cloning it, renaming etc. worked fine, but I won't release it (as you said, I do that for myself and don't want the maintaining responsibilities etc.). However thanks for your input, I guess you can close the issue.

Keep it up!

**Comment by un1versal** [comment]
Yes, that's a problem I cannot resolve, have no interest in resolving and will not resolve.

Your solution is simple, root the device and fix it yourself then when its done, you can immediately unroot it.

The solution you propose is not advised as the skin updates it will break and give you issues.

@timbooo as you can see by https://github.com/uNiversaI/revamped.themes/commits/revamp I use to do this as a skin and after a few months its very annoying to maintain and will not do it again.

The main reason I wont do it again aside form it being too time consuming is that I believe defulat skin themes should be downloadable by default and they cannot be because of skin living in where it lives.

I tried to do https://github.com/uNiversaI/confluence.extras.downloader for this purpose and also not possible because its the default skin.

you are free to do it yourself though,

Sorry but if even team kodi cant be bothered about it either and wont add this theme as a second default then there is little hope for me. See https://github.com/xbmc/xbmc/pull/5350 also another try to get this promoted... and its going no where and its not first time I try.
